version: "3"

services: 
    app: 
        build: .
        command: npm start
        ports: 
            - "8080:8080"
            - "1091:1091" 
        volumes: 
            - .:/home/node/app

        
